### ISSUE TITLE
establishing new baseline for benchmarks with "performance" scaling governor

### ISSUE THREAD

**Issue by srlantz** [cerati/mkFit#233]
We have decided to keep the CPU scaling governor setting as "performance" on phi3; it was changed it from "powersave" to "performance" sometime between July 9 and 15, which is why our multithreaded benchmarks suddenly looked a whole lot better on phi3 (see issue #232). Benchmarking results should be more consistent (and better) this way; therefore, this would be a good change to make to all our test machines.

This implies we will want to do before-and-after benchmark plots on all our test machines so that we are cognizant of the effects of making this hardware-related change globally. I propose that we do so in connection with a PR (not yet opened) where the benchmark scripts have lines added to them to verify the settings of no_turbo and scaling_governor (and possibly others), to see that they are what we expect on each machine where the benchmarks are run. Hopefully this will avoid any confusion over these settings in the future.

Previously we discussed dropping the phi1 and phi2 machines from regular benchmarking routine We could do that now (i.e., ignoring them from now on) or after the proposed PR. @dan131riley thinks that if we want to retain them for benchmarking in the future, we should make them consistent with the other machines; also these changes may have less dramatic effects on the older machines.

**Comment by srlantz** [comment]
Any comments on this issue? I especially want to know which machine(s) we would like to keep for benchmarking purposes--even if we run benchmarks on them all right now to check powersave vs. performance settings (as well as to document the performance of the "release" version of mkFit @ PR #229). Assuming we want to drop phi1 and phi2, this would be as good a time as any, I imagine.

Note, we may need to adjust the axes in the multithreaded benchmark timing plots, because on lnx7188, the latest timings fall off the bottom of the plots!

**Comment by kmcdermo** [comment]
@srlantz , in conjunction with #230 , I still have on my plate to revamp the scripts to drop phi1 and phi2 from our standard validation, but still have the option to run over them if needed.

**Comment by srlantz** [comment]
One aspect of this issue is how to ensure scaling_governor is set correctly each time the benchmarks are run. The same type of care should be taken with the no_turbo setting. Alternatives for scaling_governor:

1. Have the script do "cpupower frequency-set -g performance" on each machine before it runs the benchmarks. However, this requires all users to have sudo privileges for this command.
2. Make this setting persistent on each machine with ""tuned-adm profile throughput-performance" per @dan131riley and have the script do "cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor" to verify that the setting has not changed.

The equivalent for no_turbo:

1. Have the script do something like "echo 1 | sudo /usr/bin/tee /sys/devices/system/cpu/intel_pstate/no_turbo" on each machine before it runs the benchmarks. However, this requires either making that one piece of /sysfs world writable, or making everyone a sudoer for just that command.
2. Make this setting persistent on each machine (not sure how) and have the script do "cat /sys/devices/system/cpu/intel_pstate/no_turbo" to verify that the setting has not changed.

**Comment by srlantz** [comment]
Here is a forum post describing a way to make the no_turbo setting persist between reboots: https://classicforum.manjaro.org/index.php?PHPSESSID=825o9r2qb1a041d8n86pt87lr1&topic=26833.msg226520#msg226520

**Comment by dan131riley** [comment]
On lnx4108 and lnx7188, the scaling governor is set via `tuned-adm profile throughput-performance`, which makes the setting persistent.

Also on lnx4108 and lnx7188, the `no_turbo` file is set to world writable and turbo disabled on boot via a service defined in `/etc/systemd/system/turbo-chmod.service` containing

```
[Unit]
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=true

ExecStart=/usr/bin/chmod 666 /sys/devices/system/cpu/intel_pstate/no_turbo
ExecStart=/bin/bash -c "echo 1 >  /sys/devices/system/cpu/intel_pstate/no_turbo"

ExecStop=/usr/bin/chmod 644 /sys/devices/system/cpu/intel_pstate/no_turbo
ExecStop=/bin/bash -c "echo 0 >  /sys/devices/system/cpu/intel_pstate/no_turbo"

[Install]
WantedBy=multi-user.target
```

and made persistent via:

```
systemctl enable turbo-chmod.service
systemctl start turbo-chmod.service
```

**Comment by srlantz** [comment]
Thanks @dan131riley . But then why do we now observe that no_turbo=0 on lnx7188 and lnx4108 following the power failure and restart on 8/8/19?

**Comment by dan131riley** [comment]
Prior to around noon today, the situation was as I described on Skype, no_turbo was being made world writable but no value was being set.  The lines to set no_turbo=1 on start are a new addition, which I figured I would share as a cleaner way of changing the settings (I'm pretty sure the forum post you linked to is actually wrong, but even if it works it's an abuse of sysctl).

**Comment by srlantz** [comment]
Excellent, thanks for the clarification. I agree that the fix in the forum post is hacky at best. Your way is much better. I'd like to make the same changes to the phiN machines at UCSD if there is general agreement; then the benchmarks scripts would just need to verify that the relevant settings are still in effect (@tresreid and I can submit a PR along those lines).

**Comment by osschar** [comment]
We used to put these settings in rc.local for UCSD machines. It seems things fell apart during reinstall to centos 7.

**Comment by srlantz** [comment]
@osschar Would you (or anyone) object if I made the above changes to phi1/2/3, for the sake of consistency?

**Comment by osschar** [comment]
nope, go ahead. please also clear rc.locals on phis :)

**Comment by srlantz** [comment]
This plan has been carried out on phi1. Will attend to phi2 and phi3 as they become available.

To undo these changes and return to the usual default values for CentOS 7:

```
sudo tuned-adm profile balanced
echo 0 >  /sys/devices/system/cpu/intel_pstate/no_turbo
```

The first change is persistent and must be done/undone by a sudoer. The second change does not persist through a reboot; it can be done and undone (using "echo 1") by any user.

**Comment by kmcdermo** [comment]
Closed due to default settings ("performance") now checked by PR #238: baseline plots are posted in PR.
