### ISSUE TITLE
Possible bug in counting nFoundHits

### ISSUE THREAD

**Issue by areinsvo** [cerati/mkFit#234]
I've already mentioned this to a few people, but maybe it's good to keep track of officially too:
I ran the validation suite with mtv-require-seeds on the current head of devel and again after changing the validHitBonus from 10 to 500. The performance of STD is now fantastic (check out the plot vs number of layers), but it is totally different than the performance of CE. 

Bonus 10: http://areinsvo.web.cern.ch/areinsvo/OptV1/SIMVAL  
Bonus 50: http://areinsvo.web.cern.ch/areinsvo/OptV1_Bonus50/SIMVAL
Bonus 500: http://areinsvo.web.cern.ch/areinsvo/OptV1_Bonus500/SIMVAL 

There must be some difference in how the number of found hits is calculated between the two algorithms. Changing the hit penalty or the chi2 cut doesn’t cause any huge deviation between STD and CE. 

Looking at the nHits distributions seems to point to a bug in how NFoundHits is updated for STD:
http://areinsvo.web.cern.ch/areinsvo/OptV1_Bonus500/SIMVAL/nHits/
It’s worth pointing out that the variable being plotted here is NFoundHits_ taken from the Track object. There is no recounting of the hits associated to the track. So it’s possible that the track has a reasonable number of hits but NFoundHits_ isn’t being updated correctly.

**Comment by kmcdermo** [comment]
Wanted to link here @areinsvo slides from today's call, highlighting this issue on slide 4: https://indico.cern.ch/event/827099/contributions/3460338/attachments/1894190/3124594/OptimizeEfficiency_Aug2019.pdf

For now, we chose not to have crazy hit bonus values (which, as Allie demonstrated, we want to be lower anyways) and just print a warning in case it does happen, and then wait until Track Kaboom goes into place to resolve this for good.

**Comment by areinsvo** [comment]
This issue was kept open to remind us that the candidate scores can overflow if you try nonsensical values (like 5000) for the found hit bonus. This is resolved after [Track Kaboom in PR243](https://github.com/trackreco/mkFit/pull/243) because score is now stored as a float.
