### ISSUE TITLE
Efficiency loss for high pt tracks

### ISSUE THREAD

**Issue by areinsvo** [cerati/mkFit#248]
As discussed, there is an ~20% efficiency loss for mkFit relative to CMSSW for tracks with pt > ~50 GeV. 

This can be seen in the [standalone, MTV-like validation plots](http://areinsvo.web.cern.ch/areinsvo/MkFit/ChargeAssignment/highPt10mu_headOfDevel/SIMVAL_MTV_SEED/SKL-SP_CMSSW_TTbar_PU50_eff_pt_build_pt0p0_SIMVALSEED.png) where sim tracks are required to have a corresponding seed (plots here are with the high pt 10μ sample using the offline quadruplet seeds).

This was also seen in [Matti’s plots](https://mkortela.web.cern.ch/mkortela/tracking/mkfit/PR/PR242_mtv_quad/plots_hltOnline_hltIter0PFlowCtfWithMaterial/effandfakePtEtaPhi.pdf) using the HLT quadruplet seeds (compare black and red curves).

One (unproven) theory for the efficiency loss might be that perhaps the sizes of the search windows are too small for straight tracks that have  have small errors. For instance, as far as I can tell, there is a minimum dq value set, but there is no minimum window size in dphi. See code [here](https://github.com/trackreco/mkFit/blob/e864ed9d62251bca08cee49269b4a0e90ec4df90/mkFit/MkFinder.cc#L201).

It is important to note that for the SIMVAL_MTV_SEED plots, the ONLY way to lose efficiency is if we add incorrect hits to the track. The sim tracks in the denominator of the efficiency are required to be matched to a seed, meaning that all 4 hits in the seed belong to the sim track. See [here](https://github.com/trackreco/mkFit/blob/devel/mkFit/MkBuilder.cc#L1198-L1230). This means that if we add 0 hits to the seed, the 4-hit track will by definition be matched to the sim track and be in the numerator of our efficiency. Therefore, the efficiency loss shown in the plots above has to have a different origin than what Matevz was investigating for triplets in [PR242](https://github.com/trackreco/mkFit/pull/242).

To investigate this issue, I will make a list of specific tracks that are affected, using the high pt 10μ sample. Slava is working on remaking the 10μ sample using HLT quadruplets for seeds, so we can confirm that fixing the issue offline also fixes the issue in the HLT configuration.

**Comment by osschar** [comment]
dphi_min is taken in, see: https://github.com/trackreco/mkFit/blob/e864ed9d62251bca08cee49269b4a0e90ec4df90/mkFit/MkFinder.cc#L225

This all got a bit convoluted following several rounds of optimizations :)

**Comment by areinsvo** [comment]
Good to know. Thanks for pointing that out!

**Comment by areinsvo** [comment]
For posterity:
Matevz discovered that the affected tracks had negative entries in the covariance matrix. Manually changing the negative covariances to 1 allowed the seeds to get processed, which fixed the efficiency issue, at the expense of an increase in duplicate rate: 
11.4% before, 18.4% after for offline high pt 10muon events
8.5% before, 9.4% after for ttbar PU50 events

All of the plots can be seen in [PR250](https://github.com/trackreco/mkFit/pull/250). Once that PR gets merged, we can probably close this issue, unless people prefer to keep it open to remind ourselves to revisit the duplicate rate increase.

**Comment by areinsvo** [comment]
We no longer have a loss of efficiency at high pt, so I’m going to close this issue. I opened a [follow-up issue](https://github.com/trackreco/mkFit/issues/254) for implementing a proper fix for the negative entries in the covariance matrix.
