### ISSUE TITLE
Remove SMatrix copy

### ISSUE THREAD

**Issue by makortel** [cerati/mkFit#258]
Our copy of SMatrix
https://github.com/trackreco/mkFit/blob/devel/Math/SMatrix.h
should really be removed, or at least be hidden for the library for CMSSW.

**Comment by makortel** [comment]
The plan would be to hide the SMatrix with ifdefs and/or setting `-I` flags in the Makefile based on the presence of ROOT (e.g. if `$ROOTSYS` is defined or not).

**Comment by osschar** [comment]
Will we be able to "pass in" CMSSW ROOT to our external build?

@makortel what do you mean by having it hidden for the library? Is it being installed by cmssw external spec file?

**Comment by makortel** [comment]
> Will we be able to "pass in" CMSSW ROOT to our external build?

Yes, in the same way as TBB is passed currently (for both cases of CMS building mkFit as part of its external building procedure, and us building mkFit via "private external").

> what do you mean by having it hidden for the library? Is it being installed by cmssw external spec file?

I mean that the `Math` subdirectory would be completely ignored when mkFit is built for CMSSW.
