### ISSUE TITLE
update Makefile.config and init-env.sh for gcc8

### ISSUE THREAD

**Issue by srlantz** [cerati/mkFit#261]
Dan determined that the following steps are appropriate to run, in order to build mkFit with the gcc8 that is currently defined in init-env.sh:

source /cvmfs/cms.cern.ch/slc7_amd64_gcc820/external/tbb/2019_U9/etc/profile.d/init.sh
export TBB_PREFIX=$TBB_ROOT
make -j24 CXX=g++

The above recipe is needed to supersede the hack location for TBB that Makefile.config sets for any non-icc compiler. (1) The Makefile.config hack is undesirable and should be removed. (2) The correct TBB location should be set in the user environment; thus, the above recipe should be inserted into init-env.sh.

In addition, AVX2:=1 in Makefile.config doesn't work for gcc unless -march=native is also specified; otherwise the appropriate immintrin.h isn't found (see issue #240). This should also be fixed.

**Comment by dan131riley** [comment]
TBB_PREFIX currently overrides the compiler default, so if we set it in init-env.sh we will get TBB from cvmfs even when we're building with icc, instead of the version Intel ships with icc.  Is that what we want?

**Comment by srlantz** [comment]
I see your point, I guess the logic of Makefile.config will also need to be changed so that different things happen depending on icc vs. gcc and whether CMSSW_BASE is defined.

**Comment by makortel** [comment]
`CMSSW_BASE` is not set when CMS builds the externals.

**Comment by srlantz** [comment]
This is fixed in #262, so when that PR is merged, this issue can be closed.

Note, the existing logic in Makefie.config is left intact in PR #262; if the compiler is g++, make will check the environment for TBB_GCC, and if it exists, it will use that as the TBB_PREFIX. Therefore, TBB_GCC should not be set for clang, etc.

The resolution for the AVX2 problem turned out not to depend on the -march=native flag. The reason that flag seemed to be required for AVX2 was due to a flaw in MatriplexCommon.h, where it was actually borrowing an intrinsic from AVX512F. In PR #262, an equivalent AVX2 intrinsic was substituted. The only other change needed was to add -mfma to the compiler options, to comply with gcc's strict association between supplied x86 options and the intrinsics that are included in immintrin.h.
