### ISSUE TITLE
Update mkFit for TBB v2021.1.1 compatibility

### ISSUE THREAD

**Issue by mrodozov** [cerati/mkFit#290]
Dear devs,

we are trying to have tbb v2021.1.1 integrated for CMS externals and currently building mkFit is failing
with:
`make: *** No rule to make target 'tbb/task_scheduler_init.h', needed by 'main.o'.  Stop.`
which I cannot say this is limited to (I mean only this is missing)
ROOT are having the same issue, so they might already have a solution (haven't checked yet)
I'd like to ask if you could update mkFit for the new tbb version.
There is this deprecation document and the substitutes for the old api:
https://software.intel.com/sites/default/files/managed/b2/d2/TBBRevamp.pdf

Thank you in advance,
Cheers,
Mircho

**Comment by dan131riley** [comment]
@mrodozov I fixed the TBB deprecations on the devel branch in #286 by mostly copying what Chris did for CMSSW.  Just submitted PR #291 with the backport to the release branch.

**Comment by mrodozov** [comment]
very nice :) closing the issue
